CREATE DATABASE DATABBASE_QLTHUOC;
GO

USE DATABBASE_QLTHUOC;
GO

-- 1. Bảng Nhà Cung Cấp
CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR(10) NOT NULL PRIMARY KEY,
    TENNCC NVARCHAR(100),
    DIACHI NVARCHAR(255),
    SDT VARCHAR(15)
);
GO

-- 2. Bảng Nhân Viên
CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) NOT NULL PRIMARY KEY,
    TENNV NVARCHAR(100),
    GIOITINH NVARCHAR(10),
    NGAYVAOLAM DATE,
    SDT VARCHAR(15),
    VAITRO NVARCHAR(20) -- Quản lý / Nhân viên
);
GO

-- 3. Bảng Tài Khoản
CREATE TABLE TAIKHOAN (
    MATK VARCHAR(10) NOT NULL PRIMARY KEY,
    TENDN VARCHAR(50) UNIQUE,
    MATKHAU VARCHAR(50),
    MANV VARCHAR(10),
	VAITRO NVARCHAR(20),
    CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
G
-- 4. Bảng Khách Hàng
CREATE TABLE KHACHHANG (
    MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
    TENKH NVARCHAR(100),
    SDT VARCHAR(15),
    DIEMTICHLUY INT DEFAULT 0
);
GO

-- 5. Bảng Sản Phẩm (Thuốc)
CREATE TABLE SANPHAM (
    MASP VARCHAR(10) NOT NULL PRIMARY KEY,
    TENSP NVARCHAR(100),
    DANHMUC NVARCHAR(100),
    DANGBAOCHE NVARCHAR(50),
    QUYCACH NVARCHAR(100),
    NHASANXUAT NVARCHAR(100),
    TONKHO INT,
    GIABAN DECIMAL(18,2),
    KETOA BIT, -- 1: kê toa, 0: không
    CHIDINH NVARCHAR(255),
    CHONGCHIDINH NVARCHAR(255),
    LUUY NVARCHAR(255),
    HANSD DATE,
    MANCC VARCHAR(10),
    CONSTRAINT FK_SANPHAM_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);
GO

-- 6. Bảng Phiếu Nhập
CREATE TABLE PHIEUNHAP (
    MAPN VARCHAR(10) NOT NULL PRIMARY KEY,
    NGAYLAPPN DATE,
    TONGMATHANG INT,
    TONGTIEN DECIMAL(18,2),
    TRANGTHAI NVARCHAR(50), -- Chưa xác nhận / Đã nhận
    MANCC VARCHAR(10),
    MANV VARCHAR(10),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
    CONSTRAINT FK_PN_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

-- 7. Chi Tiết Phiếu Nhập
CREATE TABLE CHITIETPN (
    MAPN VARCHAR(10),
    MASP VARCHAR(10),
    SOLUONGNHAP INT,
    DONGIA DECIMAL(18,2),
    HANSD DATE,
    PRIMARY KEY (MAPN, MASP),
    FOREIGN KEY (MAPN) REFERENCES PHIEUNHAP(MAPN),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
GO

-- 8. Bảng Hóa Đơn
CREATE TABLE HOADON (
    MAHD VARCHAR(10) NOT NULL PRIMARY KEY,
    NGAYLAPHD DATE,
    TONGSP INT,
    GIAMGIA FLOAT,
    TONGTIEN DECIMAL(18,2),
    THANHTIEN DECIMAL(18,2),
    MAKH VARCHAR(10),
    MANV VARCHAR(10),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

-- 9. Chi Tiết Hóa Đơn
CREATE TABLE CHITIETHD (
    MAHD VARCHAR(10),
    MASP VARCHAR(10),
    SOLUONGMUA INT,
    DONGIA DECIMAL(18,2),
    PRIMARY KEY (MAHD, MASP),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
GO

-- 10. Lịch Sử Đăng Nhập
CREATE TABLE LICHSUDN (
    ID INT IDENTITY PRIMARY KEY,
    MATK VARCHAR(10),
    THOIGIANDN DATETIME,
    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
GO

-- 11. Lịch sử tích điểm
CREATE TABLE LICHSUDIEM (
    ID INT IDENTITY PRIMARY KEY,
    MAKH VARCHAR(10),
    MAHD VARCHAR(10),
    DIEMCONG INT,
    DIEMSUDUNG INT,
    NGAY DATE,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);
GO

INSERT INTO NHACUNGCAP (MANCC, TENNCC, DIACHI, SDT) VALUES 
(N'NCC01', N'Công ty Dược Hậu Giang', N'123 Đường A, Q.1, TP.HCM', N'0909123456'),
(N'NCC02', N'Công ty Traphaco', N'45 Đường B, Q.5, TP.HCM', N'0912345678'),
(N'NCC03', N'Công ty Domesco', N'67 Đường C, Q.3, TP.HCM', N'0923456789'),
(N'NCC04', N'Công ty Pymepharco', N'89 Đường D, Q.10, TP.HCM', N'0934567890'),
(N'NCC05', N'Công ty Imexpharm', N'11 Đường E, Q.7, TP.HCM', N'0945678901');

INSERT INTO NHANVIEN (MANV, TENNV, GIOITINH, NGAYVAOLAM, SDT, VAITRO) VALUES 
(N'NV01', N'Nguyễn Văn A', N'Nam', '2022-01-10', N'0901111222', N'Quản lý'),
(N'NV02', N'Trần Thị B', N'Nữ', '2023-03-05', N'0902222333', N'Nhân viên'),
(N'NV03', N'Lê Văn C', N'Nam', '2023-05-15', N'0903333444', N'Nhân viên'),
(N'NV04', N'Phạm Thị D', N'Nữ', '2024-01-02', N'0904444555', N'Nhân viên'),
(N'NV05', N'Hoàng Văn E', N'Nam', '2022-07-21', N'0905555666', N'Quản lý');


